name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cmake . --help
      - run: cmake . -DLUNASVG_BUILD_EXAMPLES=ON
      - run: make -j 2
